### ISSUE TITLE
如何上传文件到服务器？

### ISSUE THREAD

**Issue by hansong8675** [jackiehu/SwiftMesh#1]
我尝试着配置了一下，发现行不通，可否麻烦你配置一下
`  let image = UIImage.init(named:"shop_1")

        let data = image?.pngData()

        let url  = try? URL.init(from:"http://xxxxx/app/userInfo/uploadImag" as! Decoder)

        let config =  MeshMultipartConfig.formData(name:"file" , fileName:"file", fileData: data, fileURL: url, mimeType: "image/png")

        let upconfig = MeshConfig.addformData(MeshConfig)

    //MARK:上传视频
        MeshManager.shared.uploadWithConfig(configBlock:config.self) { (Progress) in
            print(Progress)
        } success: { (sucessConfig) in
            print(sucessConfig)
        } failure: { (faliureConfig) in
            print(faliureConfig)
        }`

**Comment by zjinhu** [comment]
> 我尝试着配置了一下，发现行不通，可否麻烦你配置一下
> ` let image = UIImage.init(named:"shop_1")
> 
> ```
>     let data = image?.pngData()
> 
>     let url  = try? URL.init(from:"http://xxxxx/app/userInfo/uploadImag" as! Decoder)
> 
> 
>     let config =  MeshMultipartConfig.formData(name:"file" , fileName:"file", fileData: data, fileURL: url, mimeType: "image/png")
> 
>     let upconfig = MeshConfig.addformData(MeshConfig)
> 
> 
> //MARK:上传视频
>     MeshManager.shared.uploadWithConfig(configBlock:config.self) { (Progress) in
>         print(Progress)
>     } success: { (sucessConfig) in
>         print(sucessConfig)
>     } failure: { (faliureConfig) in
>         print(faliureConfig)
>     }`
> ```

能否提供下代码，configBlock闭包内的

**Comment by hansong8675** [comment]
configblock 似乎没有配置
这是我代码的链接 https://github.com/hansong8675/ueseTemplateProject

Jackiehu <notifications@github.com> 于2020年10月20日周二 下午3:35写道：

**Comment by zjinhu** [comment]
> configblock 似乎没有配置 这是我代码的链接 https://github.com/hansong8675/ueseTemplateProject Jackiehu <notifications@github.com> 于2020年10月20日周二 下午3:35写道：
> […](#)

你需要在适配器的闭包里把表单的uploadDatas初始化，然后addformData添加表单的内容，所有的后续操作都是封装的AF内部提供的API了
